const languagesArray= ['html', 'css', 'javascript','react', 'node', 'postgres'];
console.log("languages array " + languagesArray);
const firstElement= languagesArray[0];
console.log("the first element of the array is " + firstElement);
const thirdElement= languagesArray[2];
console.log("the 3rd element of the array is " + thirdElement);
const length= languagesArray.length;
console.log('The length of the array is '+ length);
const lastElement= languagesArray[languagesArray.length-1];
console.log("The last element of the array is " + lastElement);
