let number1= '5';
let number2= '6';
let product= number1 * number2;
console.log(product);
console.log(typeof product);
let charge= '7';
let payment= '3';
let amountRemaining= payment-charge;
console.log(amountRemaining);
console.log(typeof amountRemaining);
let tests= '1';
let assignments='2';
let final='3';
let grade= ((tests+assignments+final)/3);
console.log(grade);
console.log(typeof grade);
let firstName= 'Kayla';
let lastName= 'Cloud';
let fullName= 'firstName + lastName';
console.log(fullName);
console.log(typeof fullName);
let pH= '4';
let isAcidic=(pH<8);
console.log(isAcidic);
console.log(typeof isAcidic);
let numberOfSoliders = '100';
let isSparta= ('numberOfSoliders'===300);
console.log(isSparta);
console.log(typeof isSparta);
let nickname= 'firstName + lastName';
nickname +='is the GOAT';
console.log(nickname);
console.log (typeof nickname);
